### ISSUE TITLE
Village data

### ISSUE THREAD

**Issue by Jonty** [emfcamp/developer.emfcamp.org#11]
List of villages + descriptions + lat/lon etc

**Comment by marksteward** [comment]
This already exists at https://www.emfcamp.org/api/map/villages, but it only includes villages with locations.

If someone wants to add a list of all villages, the following code will be helpful:

https://github.com/emfcamp/Website/blob/main/apps/api/map.py#L1-L11
https://github.com/emfcamp/Website/blob/main/apps/api/map.py#L67
https://github.com/emfcamp/Website/blob/main/models/village.py#L52-L55

**Comment by marksteward** [comment]
See https://github.com/emfcamp/Website/blob/main/apps/api/villages.py#L88-L91, e.g. https://www.emfcamp.org/api/villages.
