### ISSUE TITLE
Document MQTT

### ISSUE THREAD

**Issue by Jonty** [emfcamp/developer.emfcamp.org#15]
Not sure what hostname/topics this has yet

**Comment by andypiper** [comment]
Happy to do this, but need connection info. It looks like there's a host `mqtt.emf.camp` but I don't know anything further - where can I find that? (asked on IRC as well)

**Comment by jellybob** [comment]
Hope is for MQTT to be up at some point today, it doesn't exist yet.

**Comment by flyte** [comment]
Hey, is MQTT up now?

**Comment by elstanto** [comment]
MQTT is up

**Comment by andypiper** [comment]
The live captioning page says that the captions are (intended to be) published to a topic, but I'm not seeing that on the broker, just the venue statistics on wifi, humidity, power etc. If that's no longer the case I can nix it from the live captioning doc.
